### ISSUE TITLE
Danish language doesn't work. 

### ISSUE THREAD

**Issue by dadiorchen** [iamcco/coc-cspell-dicts#1]
```
{
  "coc.preferences.formatOnSaveFiletypes": ["javascript"],

  "javascript.format.enabled": true,
  "javascript.suggestionActions.enabled": false,
  "tsserver.enable": true,

  "cSpell.userWords": [
    "Corebuis",
    "Dadior",
    "Formik",
    "cloudinary",
    "dadiorchen",
    "devtool",
    "nocheck",
    "testid"
  ],
  "cSpellExt.enableDictionaries": ["danish", "dutch"],
  "cSpell.language": "en,dk,nl"
}
```
After setting the config:   
"cSpellExt.enableDictionaries": ["danish", "dutch"],
  "cSpell.language": "en,dk,nl"

cSpell still can not recognize the Danish language:
![image](https://user-images.githubusercontent.com/5744708/84360540-d44ac680-abfc-11ea-8ad3-a1f7eb48a67a.png)

**Comment by danielnielsennumber1** [comment]
I had the same problem.
It seems to work with da not dk

**Comment by ModProg** [comment]
> I had the same problem.
> It seems to work with da not dk

This is then a documentation error, as `da` is the correct languagecode:
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=da
